name: jest-tests
on: [push]
jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
    - run: echo "starting frontend tests"
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: cd client
    - run: npm ci && npm run test
