name: test-pipeline
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies at Root
        run: yarn install

      - name: Assert synced dependencies
        run: yarn syncpack list mismatches

      - name: Check architecture
        run: yarn run architecture-tests

      - name: Backend Tests
        working-directory: ./backend
        run: yarn test

      - name: Domain Tests
        working-directory: ./domain
        run: yarn test

      - name: Frontend Tests
        working-directory: ./frontend
        run: yarn run test
